version: '3.3'

services:
    web:
        restart: always
        build: .
        volumes:
            - ./codes:/home/web/codes
            - /opt/pysfapp/media:/home/web/codes/media
        ports:
            - 8040:8000
        command: bash -c "python3 manage.py runserver 0.0.0.0:8000"
        # command: bash -c "/usr/local/bin/gunicorn --bind :8000 --timeout 999 --workers 8 --env DJANGO_SETTINGS_MODULE=web.settings  web.wsgi:application"

        entrypoint: /entrypoint.sh
        networks:
            - backend

    redis:
        restart: always
        image: redis
        hostname: redis
        volumes:
           - /opt/redis-app:/data
           - ./codes:/home/web/codes
        networks:
            - backend

networks:
    backend:
        external: false
            #  name: api_network

