# Generated by Django 3.2.10 on 2023-10-25 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vconf', '0018_auto_20220919_1356'),
    ]

    operations = [
    ]
